import { Product } from './types/Product'

export const sampleProducts: Product[] = [
  {
    name: 'Samsung S24',
    slug: 'Samsung-s24',
    image: '../images/s24.jpg',
    price: 200000,
    countInStock: 25,
    brand: 'Samsung',
    rating: 4.5,
    numReviews: 10,
    description: 'Worlds Number One Smart Phone',
    category: 'Smartphones',
  },
  {
    name: 'iPhone 14',
    slug: 'iPhone-24',
    image: '../images/iphone14.jpg',
    price: 200000,
    countInStock: 20,
    brand: 'Apple',
    rating: 4.8,
    numReviews: 15,
    description: 'A powerful phone with the best camera',
    category: 'Smartphones',
  },
  {
    name: 'Google Pixel 8',
    slug: 'Google-Pixel-8',
    image: '../images/pixel8.jpg',
    price: 150000,
    countInStock: 15,
    brand: 'Google',
    rating: 4.6,
    numReviews: 12,
    description: 'Amazing camera and stock Android experience',
    category: 'Smartphones',
  },

  {
    name: 'Samsung Galaxy Watch',
    slug: 'Samsung-Galaxy-Watch',
    image: '../images/galaxywatch.jpg',
    price: 100000,
    countInStock: 30,
    brand: 'Samsung',
    rating: 4.7,
    numReviews: 8,
    description: 'Stay connected with a smartwatch',
    category: 'Wearable Technology',
  },
  {
    name: 'Apple MacBook Pro',
    slug: 'Apple-MacBook-Pro',
    image: '../images/macbookpro.jpg',
    price: 400000,
    countInStock: 0,
    brand: 'Apple',
    rating: 4.9,
    numReviews: 20,
    description: 'Powerful laptop for professionals',
    category: 'Laptops',
  },
  {
    name: 'ASUS G14',
    slug: 'ASUS-G!$',
    image: '../images/asus14.jpg',
    price: 300000,
    countInStock: 8,
    brand: 'Dell',
    rating: 4.7,
    numReviews: 18,
    description: 'Thin and powerful laptop',
    category: 'Laptops',
  },
]
